- name: copy all files and directories
  become: true 
  synchronize:
    src: "{{ home_dir }}"
    dest: "{{ dest_dir }}"
    rsync_opts:
      # - "--exclude=.git/"
      - "--exclude=.gitignore"
      - "--exclude=README.md"
      - "--exclude=ansible/"
      - "--exclude=venv/"
  when : COPY == True

- name: run when COPY variable is not True :)
  debug:
    msg: "COPY varialbe is not True, sir :/"
  when: COPY != True