- name: Deploy monitoring service
  ansible.builtin.shell: |
    sudo apt-get update
    sudo apt-get install -y prometheus
    sudo systemctl start prometheus

- name: Wait for Prometheus to be ready
  ansible.builtin.wait_for:
    port: 9090
    state: started
    timeout: 300